name: amplessimus
description: A good way of looking at Untis substitution plans using DSBMobile.

# Don't publish to pub.
publish_to: 'none'

# a.b.c+build_number
# Overridden in flutter build by --build-name and --build-number.
# Android: build-name = versionName, build-number = versionCode.
# https://developer.android.com/studio/publish/versioning
# iOS: build-name = CFBundleShortVersionString, build-number = CFBundleVersion.
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.0-1

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.3
  crypto: ^3.0.0
  url_launcher: ^6.0.2
  dsbuntis: ^3.1.0
  schttp: ^1.1.0
  update: ^0.1.1-nullsafety.0
  html_search: ^0.1.1
  flutter_svg: ^0.21.0-nullsafety.0
  package_info: ^2.0.0
  touch_bar: ^0.0.1-alpha.4

dependency_overrides:
  touch_bar:
    git:
      url: https://github.com/Ampless/touch_bar_flutter_plugin.git
      path: touch_bar
  touch_bar_platform_interface:
    git:
      url: https://github.com/Ampless/touch_bar_flutter_plugin.git
      path: touch_bar_platform_interface
  touch_bar_macos:
    git:
      url: https://github.com/Ampless/touch_bar_flutter_plugin.git
      path: touch_bar_macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: ^0.8.1
  pedantic: ^1.11.0
  github: ^8.0.1
  path: ^1.8.0-nullsafety.3

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/logo.svg"

flutter:

  # Make sure that the Material Icons font is included.
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/home.png
    - assets/settings.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # https://flutter.dev/custom-fonts/#from-packages
